* openswan-cisco-738385.patch

diff --git a/programs/_updown.netkey/_updown.netkey.in b/programs/_updown.netkey/_updown.netkey.in
--- a/programs/_updown.netkey/_updown.netkey.in
+++ b/programs/_updown.netkey/_updown.netkey.in
@@ -179,6 +179,14 @@ downroute() {
     ip route flush cache
 }
 
+downrule() {
+        if [ -n "$PLUTO_MY_SOURCEIP" ]
+        then
+            doroute del
+            ip route flush cache
+        fi
+}
+
 updateresolvconf() {
 
 if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
@@ -289,15 +297,13 @@ disconnectNM() {
 addsource() {
     st=0
     # check if given sourceip is local and add as alias if not
-    saddr=${PLUTO_MY_SOURCEIP%/*}/32
-    if test "${PLUTO_PEER_CLIENT##*/}" != 32
-    then
-	saddr=${PLUTO_MY_SOURCEIP%/*}/"${PLUTO_PEER_CLIENT##*/}"
-    fi
+    if ! ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local; then
 
-    if ! ip addr show dev ${PLUTO_INTERFACE%:*} | grep -qs "inet ${saddr}"
-    then
-	it="ip addr add ${saddr} dev ${PLUTO_INTERFACE%:*}"
+	if [ -z "$PLUTO_IS_PEER_CISCO" -o "$PLUTO_IS_PEER_CISCO" = 0 ]; then
+	it="ip addr add ${PLUTO_MY_SOURCEIP%/*}/32 dev ${PLUTO_INTERFACE%:*}"
+	else
+	it="ip addr add ${PLUTO_MY_SOURCEIP%/*}/${PLUTO_PEER_CLIENT##*/} dev ${PLUTO_INTERFACE%:*}"
+	fi
 	oops="`eval $it 2>&1`"
 	st=$?
 	if [ " $oops" = " " -a " $st" != " 0" ]; then
@@ -320,17 +326,9 @@ addsource() {
 
 delsource() {
     st=0
-    # check if given sourceip is local and add as alias if not
+    # check if given sourceip is local 
     if  ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local; then
-        #it="ip addr del ${PLUTO_MY_SOURCEIP%/*}/32 label ${PLUTO_INTERFACE%:*}:1 dev ${PLUTO_INTERFACE%:*}"
-
-                saddr=${PLUTO_MY_SOURCEIP%/*}/32
-                if test "${PLUTO_PEER_CLIENT##*/}" != 32
-                then
-                saddr=${PLUTO_MY_SOURCEIP%/*}/"${PLUTO_PEER_CLIENT##*/}"
-                fi
-
-        it="ip addr del ${saddr} dev ${PLUTO_INTERFACE%:*}"
+        it="ip addr del ${PLUTO_MY_SOURCEIP%/*}/${PLUTO_PEER_CLIENT##*/} dev ${PLUTO_INTERFACE%:*}"
 
         oops="`eval $it 2>&1`"
         st=$?
@@ -346,7 +344,7 @@ delsource() {
                 ;;
         esac
         if [ " $oops" != " " -o " $st" != " 0" ]; then
-            echo "$0: addsource \`$it' failed ($oops)" >&2
+            echo "$0: delsource \`$it' failed ($oops)" >&2
         fi
     fi
     return $st
@@ -391,8 +389,10 @@ doroute() {
 	parms2="$parms2 src ${PLUTO_MY_SOURCEIP%/*}"
     fi
 
+    if [ -z "$PLUTO_IS_PEER_CISCO" -o "$PLUTO_IS_PEER_CISCO" = 1 ]; then 
     if [ "$1" = "del" -a -n "$PLUTO_MY_SOURCEIP" ]; then
         delsource
+    fi
     fi
 
     case "$PLUTO_PEER_CLIENT" in
@@ -438,6 +438,7 @@ case "$PLUTO_VERB" in
 	;;
     down-host)
 	# connection to me going down
+	downrule
 	# If you are doing a custom version, firewall commands go here.
 	;;
     up-client)
@@ -446,6 +447,7 @@ case "$PLUTO_VERB" in
 	;;
     down-client)
 	# connection to my client subnet going down
+	downrule
 	# If you are doing a custom version, firewall commands go here.
 	;;
     updateresolvconf-host|updateresolvconf-client)
