Fixes to bogus chars in updown scripts.

diff --git a/programs/_updown.netkey/_updown.ip2.in b/programs/_updown.netkey/_updown.ip2.in
--- a/programs/_updown.netkey/_updown.ip2.in
+++ b/programs/_updown.netkey/_updown.ip2.in
@@ -2,9 +2,9 @@
 # iproute2 version, default updown script
 #
 # Copyright (C) 2003-2004 Nigel Metheringham
-# Copyright (C) 2002-2007 Michael Richardson <mcr@xelerance.com>
-# Copyright (C) 2003-2007 Tuomo Soini <tis@foobar.fi>
-# Copyright (C) 2003-2007 Paul Wouters <paul@xelerance.com>
+# Copyright (C) 2002-2004 Michael Richardson <mcr@xelerance.com>
+# Copyright (C) 2007-2008 Paul Wouters <paul@xelerance.com>
+# Copyright (C) 2003-2008 Tuomo Soini <tis@foobar.fi>
 # 
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -17,389 +17,319 @@
 # for more details.
 #
 
-# Note: Lots of klips code not called, and can be removed.
-
 # CAUTION:  Installing a new version of Openswan will install a new
 # copy of this script, wiping out any custom changes you make.  If
 # you need changes, make a copy of this under another name, and customize
 # that, and use the (left/right)updown parameters in ipsec.conf to make
 # Openswan use yours instead of this default one.
 
-LC_ALL=C export LC_ALL
+LC_ALL=C
+export LC_ALL
 
-# things that this script gets (from ipsec_pluto(8) man page)
+# Things that this script gets (from ipsec_pluto(8) man page)
 #
 #
-#      PLUTO_VERSION
-#              indicates  what  version of this interface is being
-#              used.  This document describes version  1.1.   This
-#              is upwardly compatible with version 1.0.
+#	PLUTO_VERSION
+#		indicates  what	 version of this interface is being
+#		used.  This document describes version	1.1.   This
+#		is upwardly compatible with version 1.0.
 #
-#       PLUTO_VERB
-#              specifies the name of the operation to be performed
-#              (prepare-host, prepare-client, up-host, up-client,
-#              down-host, or down-client).  If the address family
-#              for security gateway to security gateway 
-#              communications is IPv6, then a suffix of -v6 is added
-#              to the verb.
+#	PLUTO_VERB
+#		specifies the name of the operation to be performed
+#		(prepare-host, prepare-client, up-host, up-client,
+#		down-host, or down-client).  If the address family
+#		for security gateway to security gateway
+#		communications is IPv6, then a suffix of -v6 is added
+#		to the verb.
 #
-#       PLUTO_CONNECTION
-#              is the name of the  connection  for  which  we  are
-#              routing.
+#	PLUTO_CONNECTION
+#		is the name of the  connection	for  which  we	are
+#		routing.
 #
-#       PLUTO_CONN_POLICY
-#              the policy of the connection, as in:
-#     RSASIG+ENCRYPT+TUNNEL+PFS+DONTREKEY+OPPORTUNISTIC+failureDROP+lKOD+rKOD  
+#	PLUTO_CONN_POLICY
+#		the policy of the connection, as in:
+#		RSASIG+ENCRYPT+TUNNEL+PFS+DONTREKEY+OPPORTUNISTIC
+#		+failureDROP+lKOD+rKOD	
 #
-#       PLUTO_NEXT_HOP
-#              is the next hop to which packets bound for the peer
-#              must be sent.
+#	PLUTO_NEXT_HOP
+#		is the next hop to which packets bound for the peer
+#		must be sent.
 #
-#       PLUTO_INTERFACE
-#              is the name of the ipsec interface to be used.
+#	PLUTO_INTERFACE
+#		is the name of the ipsec interface to be used.
 #
-#       PLUTO_ME
-#              is the IP address of our host.
+#	PLUTO_ME
+#		is the IP address of our host.
 #
-#       PLUTO_MY_CLIENT
-#              is the IP address / count of our client subnet.  If
-#              the  client  is  just  the  host,  this will be the
-#              host's own IP address / max (where max  is  32  for
-#              IPv4 and 128 for IPv6).
+#	PLUTO_MY_CLIENT
+#		is the IP address / count of our client subnet.	 If
+#		the  client  is	 just  the  host,  this will be the
+#		host's own IP address / max (where max	is  32	for
+#		IPv4 and 128 for IPv6).
 #
-#       PLUTO_MY_CLIENT_NET
-#              is the IP address of our client net.  If the client
-#              is just the host, this will be the  host's  own  IP
-#              address.
+#	PLUTO_MY_CLIENT_NET
+#		is the IP address of our client net.  If the client
+#		is just the host, this will be the  host's  own	 IP
+#		address.
 #
-#       PLUTO_MY_CLIENT_MASK
-#              is  the  mask for our client net.  If the client is
-#              just the host, this will be 255.255.255.255.
+#	PLUTO_MY_CLIENT_MASK
+#		is  the	 mask for our client net.  If the client is
+#		just the host, this will be 255.255.255.255.
 #
-#       PLUTO_MY_SOURCEIP
-#              if non-empty, then the source address for the route will be
-#              set to this IP address.
+#	PLUTO_MY_SOURCEIP
+#		if non-empty, then the source address for the route will be
+#		set to this IP address.
 #
-#       PLUTO_MY_PROTOCOL
-#              is the protocol  for this  connection.  Useful  for
-#              firewalling.
+#	PLUTO_MY_PROTOCOL
+#		is the protocol	 for this  connection.	Useful	for
+#		firewalling.
 #
-#       PLUTO_MY_PORT
-#              is the port. Useful for firewalling.
+#	PLUTO_MY_PORT
+#		is the port. Useful for firewalling.
 #
-#       PLUTO_PEER
-#              is the IP address of our peer.
+#	PLUTO_PEER
+#		is the IP address of our peer.
 #
-#       PLUTO_PEER_CLIENT
-#              is the IP address / count of the peer's client subnet.
-#               If the client is just the peer, this will be
-#              the peer's own IP address / max (where  max  is  32
-#              for IPv4 and 128 for IPv6).
+#	PLUTO_PEER_CLIENT
+#		is the IP address / count of the peer's client subnet.
+#		If the client is just the peer, this will be
+#		the peer's own IP address / max (where	max  is	 32
+#		for IPv4 and 128 for IPv6).
 #
-#       PLUTO_PEER_CLIENT_NET
-#              is the IP address of the peer's client net.  If the
-#              client is just the peer, this will  be  the  peer's
-#              own IP address.
+#	PLUTO_PEER_CLIENT_NET
+#		is the IP address of the peer's client net.  If the
+#		client is just the peer, this will  be	the  peer's
+#		own IP address.
 #
-#       PLUTO_PEER_CLIENT_MASK
-#              is  the  mask  for  the  peer's client net.  If the
-#              client   is   just   the   peer,   this   will   be
-#              255.255.255.255.
+#	PLUTO_PEER_CLIENT_MASK
+#		is  the	 mask  for  the	 peer's client net.  If the
+#		client	 is   just   the   peer,   this	  will	 be
+#		255.255.255.255.
 #
-#       PLUTO_PEER_PROTOCOL
-#              is  the  protocol  set  for  remote  end  with port
-#              selector.
+#	PLUTO_PEER_PROTOCOL
+#		is  the	 protocol  set	for  remote  end  with port
+#		selector.
 #
-#       PLUTO_PEER_PORT
-#              is the peer's port. Useful for firewalling.
+#	PLUTO_PEER_PORT
+#		is the peer's port. Useful for firewalling.
 #
-#       PLUTO_CONNECTION_TYPE
+#	PLUTO_CONNECTION_TYPE
 #
 #	PLUTO_PROTO_STACK
-#		the kernel level IPsec stack pluto is using
+#		is the local IPsec kernel stack used, eg KLIPS, NETKEY,
+#		NOSTACK
 
-# Import default _updown configs from the /etc/sysconfig/pluto_updown file
-#
-# Two variables can be set in this file:
-#
-#       DEFAULTSOURCE
-#              is the default value for PLUTO_MY_SOURCEIP
-#
-#       IPROUTETABLE
-#              is the default value for IPROUTETABLE
-#
-#       IPROUTEARGS
-#              is the extra argument list for ip route command
-#
-#       IPRULEARGS
-#              is the extra argument list for ip rule command
-#
-if [ -f /etc/sysconfig/pluto_updown ]
-then
-    . /etc/sysconfig/pluto_updown
+# Ignore parameter custom
+if [ " $1" = " custom" ]; then
+    shift
 fi
 
-# check interface version
-case "$PLUTO_VERSION" in
-1.*)	# Older Pluto?!?  Play it safe, script may be using new features.
-	echo "$0: obsolete interface version \`$PLUTO_VERSION'," >&2
-	echo "$0: 	called by obsolete Pluto?" >&2
-	exit 2
-	;;
-2.*)	;;
-*)	echo "$0: unknown interface version \`$PLUTO_VERSION'" >&2
-	exit 2
-	;;
-esac
-
-# check parameter(s)
-case "$1:$*" in
-':')			# no parameters
-	;;
-custom:*)		# custom parameters (see above CAUTION comment)
-	;;
-*)	echo "$0: unknown parameters \`$*'" >&2
-	exit 2
-	;;
-esac
-
+while [ $# -gt 0 ]; do
+    case $1 in
+	--route)
+	    case $2 in
+		[Yy]*)
+		    ROUTE=yes
+		    ;;
+		*)
+		    ROUTE=
+		    ;;
+	    esac
+	    shift; shift
+	    ;;
+	--iproute)
+	    IPRARGS="$2"
+	    shift; shift
+	    ;;
+	*)
+	    echo "$0: Unknown argument \"$1\"" >&2
+	    exit 1
+	    ;;
+    esac
+done
+	    
 # utility functions for route manipulation
-
-uprule() {
-	# policy based advanced routing
-	if [ -n "$IPROUTETABLE" ]
-	then
-	    dorule delete
-	    dorule add
-	fi
-	# virtual sourceip support
-	if [ -n "$PLUTO_MY_SOURCEIP" ]
-	then
-	    addsource
-	    changesource
-	fi
-	ip route flush cache
+# Meddling with this stuff should not be necessary and requires great care.
+uproute() {
+    doroute replace
+    ip route flush cache
 }
 
-downrule() {
-	if [ -n "$PLUTO_MY_SOURCEIP" ]
-	then
-	    dorule delete
-	    ip route flush cache
-	fi
+
+downroute() {
+    doroute del
+    ip route flush cache
 }
+
 
 addsource() {
-	st=0
-	#
-	# Fix for Bug #66215 to solve SNAT/MASQUERADE problems with recent
-	# 2.6.x kernels.
-	# Instead of a /32 it seems better to use the netmask of the remote
-	# (peer) network for the sourceip as suggested by Patrick McHardy.
-	#
-	cidr=${PLUTO_PEER_CLIENT##*/}
-	snet=${PLUTO_MY_SOURCEIP%/*}/32
-	if test "${PLUTO_PEER_CLIENT}" != "${cidr}"
-	then
-		snet=${PLUTO_MY_SOURCEIP%/*}/${cidr}
+    st=0
+    # check if given sourceip is local and add as alias if not
+    if ! ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local; then
+	it="ip addr add ${PLUTO_MY_SOURCEIP%/*}/32 dev ${PLUTO_INTERFACE%:*}"
+	oops="`eval $it 2>&1`"
+	st=$?
+	if [ " $oops" = " " -a " $st" != " 0" ]; then
+	    oops="silent error, exit status $st"
 	fi
-	if ! ip addr show dev ${PLUTO_INTERFACE%:*} | grep -qs "inet ${snet}"
-	then
-		it="ip addr add ${snet} dev ${PLUTO_INTERFACE%:*}"
-
-	    oops="`eval $it 2>&1`"
-	    st=$?
-	    if test " $oops" = " " -a " $st" != " 0"
-	    then
-		oops="silent error, exit status $st"
-	    fi
-	    case "$oops" in
-		'RTNETLINK answers: File exists'*)
+	case "$oops" in
+	    'RTNETLINK answers: File exists'*)
 		# should not happen, but ... ignore if the
 		# address was already assigned on interface
 		oops=""
 		st=0
-	    ;;
-	    esac
-	    if test " $oops" != " " -o " $st" != " 0"
-	    then
-		echo "$0: addsource \`$it' failed ($oops)" >&2
-	    fi
+		;;
+	esac
+	if [ " $oops" != " " -o " $st" != " 0" ]; then
+	    echo "$0: addsource \`$it' failed ($oops)" >&2
 	fi
-	return $st
+    fi
+    return $st
 }
 
-changesource() {
-	st=0
-	parms="$PLUTO_PEER_CLIENT"
-	parms2="dev $PLUTO_INTERFACE"
-	parms3="src ${PLUTO_MY_SOURCEIP%/*}" 
-	if [ -n "$IPROUTETABLE" ]
-	then
-	    parms3="$parms3 table $IPROUTETABLE"
-	fi
-	cmd=replace
-	it="ip route $cmd $parms $parms2 $parms3"
- 	case "$PLUTO_PEER_CLIENT" in
- 	"0.0.0.0/0")
-		# opportunistic encryption work around
-		it=
- 		;;
- 	esac
-	oops="`eval $it 2>&1`"
- 	st=$?
-	if test " $oops" = " " -a " $st" != " 0"
- 	then
-	    oops="silent error, exit status $st"
-	fi
-	if test " $oops" != " " -o " $st" != " 0"
-	then
-	    echo "$0: changesource \`$it' failed ($oops)" >&2
- 	fi
- 	return $st
-}
 
-dorule() {
-	st=0
-	it2=
-	iprule="from $PLUTO_MY_CLIENT"
-	iprule2="to $PLUTO_PEER_CLIENT"
-	if [ -n "$IPROUTETABLE" ]
-	then
-	    iprule2="$iprule2 table $IPROUTETABLE"
-	fi
-	iprule2="$iprule2 $IPRULEARGS"
+doroute() {
+    st=0
+    # skip routing if it's not enabled or necessary
+    if [ " $PLUTO_MY_SOURCEIP" = " " -a " $ROUTE" != " yes" ]; then
+	return 0
+    fi
+    parms="$PLUTO_PEER_CLIENT"
+    parms2=$IPRARGS
+    # use nexthop if (right/left)nexthop is set and nexthop is not %direct
+    if [ -n "$PLUTO_NEXT_HOP" -a "$PLUTO_NEXT_HOP" != "$PLUTO_PEER" ]; then
+	parms2="via $PLUTO_NEXT_HOP"
+    fi
 
-	case "$PLUTO_PEER_CLIENT" in
+    # old: route via pluto_interface
+    # parms2="$parms2 dev ${PLUTO_INTERFACE%:*} $IPROUTEARGS"
+    # new: route via proper interface according to routing table
+    PLUTO_PEER_INTERFACE=`ip -o route get $PLUTO_PEER | sed "s/^.*dev \([^ ]*\) .*/\1/"`
+    if [ -z "$PLUTO_PEER_INTERFACE" ]; then
+	PLUTO_PEER_INTERFACE=$PLUTO_INTERFACE
+    fi
+    parms2="$parms2 dev ${PLUTO_PEER_INTERFACE%:*} $IPROUTEARGS"
+
+    # make sure whe have sourceip locally in this machine
+    if [ "$1" = "replace" -a -n "$PLUTO_MY_SOURCEIP" ]; then
+	addsource
+	# use sourceip as route default source
+	parms2="$parms2 src ${PLUTO_MY_SOURCEIP%/*}"
+    fi
+
+    case "$PLUTO_PEER_CLIENT" in
 	"0.0.0.0/0")
-		# opportunistic encryption work around
-		st=0
-		;;
+	    # opportunistic encryption work around
+	    # need to provide route that eclipses default, without 
+	    # replacing it.
+	    it="ip route $1 0.0.0.0/1 $parms2 &&
+			ip route $1 128.0.0.0/1 $parms2"
+	    ;;
 	*)
-		if [ -z "$PLUTO_MY_SOURCEIP" ]
-		then
-		    if [ "$PLUTO_ME" = "${PLUTO_MY_CLIENT%/*}" ]
-		    then
-			it="ip rule $1 iif lo $iprule2"
-		    else
-			it="ip rule $1 $iprule $iprule2"
-		    fi
-		else
-		    if [ "${PLUTO_MY_SOURCEIP%/*}" = "${PLUTO_MY_CLIENT%/*}" ]
-		    then
-			it="ip rule $1 iif lo $iprule2"
-		    else
-			it="ip rule $1 $iprule $iprule2"
-			it2="ip rule $1 iif lo $iprule2"
-		    fi
-		fi
-		oops="`eval $it 2>&1`"
-		st=$?
-		if test " $oops" = " " -a " $st" != " 0"
-		then
-		    oops="silent error, exit status $st"
-		fi
-		case "$oops" in
-		'RTNETLINK answers: No such process'*)
-			# This is what ip rule gives
-			# for "could not find such a rule"
-			oops=
-			st=0
-			;;
-		esac
-		if test " $oops" != " " -o " $st" != " 0"
-		then
-		    echo "$0: dorule \`$it' failed ($oops)" >&2
-		fi
-		if test "$st" = "0" -a -n "$it2"
-		then
-		    oops="`eval $it2 2>&1`"
-		    st=$?
-		    if test " $oops" = " " -a " $st" != " 0"
-		    then
-			oops="silent error, exit status $st"
-		    fi
-		    case "$oops" in
-		    'RTNETLINK answers: No such process'*)
-			    # This is what ip rule gives
-			    # for "could not find such a rule"
-			    oops=
-			    st=0
-			    ;;
-		    esac
-		    if test " $oops" != " " -o " $st" != " 0"
-		    then
-			echo "$0: dorule \`$it2' failed ($oops)" >&2
-		    fi
-		fi
-		;;
-	    esac
-	return $st
+	    it="ip route $1 $parms $parms2"
+	    ;;
+    esac
+    oops="`eval $it 2>&1`"
+    st=$?
+    if [ " $oops" = " " -a " $st" != " 0" ]; then
+	oops="silent error, exit status $st"
+    fi
+    if [ " $oops" != " " -o " $st" != " 0" ]; then
+	echo "$0: doroute \`$it' failed ($oops)" >&2
+    fi
+    return $st
 }
+ 
 
 # the big choice
-case "$PLUTO_VERB:$1" in
-prepare-host:*|prepare-client:*)
-	# not used in netkey
+case "$PLUTO_VERB" in
+    prepare-host|prepare-client)
+	# delete possibly-existing route (preliminary to adding a route)
+	case "$PLUTO_PEER_CLIENT" in
+	    "0.0.0.0/0")
+		# need to provide route that eclipses default, without 
+		# replacing it.
+		parms1="0.0.0.0/1"
+		parms2="128.0.0.0/1"
+		it="ip route del $parms1 $IPROUTEARGS 2>&1 ; ip route del $parms2 $IPROUTEARGS 2>&1"
+		oops="`ip route del $parms1 $IPROUTEARGS 2>&1 ; ip route del $parms2 $IPROUTEARGS 2>&1`"
+		;;
+	    *)
+		parms="$PLUTO_PEER_CLIENT $IPROUTEARGS"
+		it="ip route del $parms 2>&1"
+		oops="`ip route del $parms 2>&1`"
+		;;
+	esac
+	status="$?"
+	if [ " $oops" = " " -a " $status" != " 0" ]; then
+		oops="silent error, exit status $status"
+	fi
+	case "$oops" in
+	    *'RTNETLINK answers: No such process'*)	
+		# This is what route (currently -- not documented!) gives
+		# for "could not find such a route".
+		oops=
+		status=0
+		;;
+	esac
+	if [ " $oops" != " " -o " $status" != " 0" ]; then
+	    echo "$0: \`$it' failed ($oops)" >&2
+	fi
+	exit $status
 	;;
-route-host:*|route-client:*)
+    route-host|route-client)
 	# connection to me or my client subnet being routed
-	#uproute
+	uproute
 	;;
-unroute-host:*|unroute-client:*)
+    unroute-host|unroute-client)
 	# connection to me or my client subnet being unrouted
-	#downroute
+	downroute
 	;;
-up-host:*)
-	# connection to me coming up
-	uprule
-	# If you are doing a custom version, firewall commands go here.
-	;;
-down-host:*)
-	# connection to me going down
-	downrule
-	# If you are doing a custom version, firewall commands go here.
-	;;
-up-client:)
-	# connection to my client subnet coming up
-	uprule
-	# If you are doing a custom version, firewall commands go here.
-	;;
-down-client:)
-	# connection to my client subnet going down
-	downrule
-	# If you are doing a custom version, firewall commands go here.
-	;;
-#
-# IPv6
-#
-prepare-host-v6:*|prepare-client-v6:*)
-	;;
-route-host-v6:*|route-client-v6:*)
-	# connection to me or my client subnet being routed
-	#uproute_v6
-	;;
-unroute-host-v6:*|unroute-client-v6:*)
-	# connection to me or my client subnet being unrouted
-	#downroute_v6
-	;;
-up-host-v6:*)
+    up-host)
 	# connection to me coming up
 	# If you are doing a custom version, firewall commands go here.
 	;;
-down-host-v6:*)
+    down-host)
 	# connection to me going down
 	# If you are doing a custom version, firewall commands go here.
 	;;
-up-client-v6:)
+    up-client)
 	# connection to my client subnet coming up
 	# If you are doing a custom version, firewall commands go here.
 	;;
-down-client-v6:)
+    down-client)
 	# connection to my client subnet going down
 	# If you are doing a custom version, firewall commands go here.
 	;;
-*)	echo "$0: unknown verb \`$PLUTO_VERB' or parameter \`$1'" >&2
+    #
+    # IPv6
+    #
+    prepare-host-v6|prepare-client-v6)
+	# prepare client for connection
+	;;
+    route-host-v6|route-client-v6)
+	# connection to me or my client subnet being routed
+	;;
+    unroute-host-v6|unroute-client-v6)
+	# connection to me or my client subnet being unrouted
+	;;
+    up-host-v6)
+	# connection to me coming up
+	# If you are doing a custom version, firewall commands go here.
+	;;
+    down-host-v6)
+	# connection to me going down
+	# If you are doing a custom version, firewall commands go here.
+	;;
+    up-client-v6)
+	# connection to my client subnet coming up
+	# If you are doing a custom version, firewall commands go here.
+	;;
+    down-client-v6)
+	# connection to my client subnet going down
+	# If you are doing a custom version, firewall commands go here.
+	;;
+    *)	echo "$0: unknown verb \`$PLUTO_VERB' or parameter \`$1'" >&2
 	exit 1
 	;;
 esac
