make clean gave an error when USE_IPROUTE2 was false

diff --git a/programs/_updown.netkey/Makefile b/programs/_updown.netkey/Makefile
--- a/programs/_updown.netkey/Makefile
+++ b/programs/_updown.netkey/Makefile
@@ -21,20 +21,19 @@ PROGRAMDIR=${LIBDIR}
 
 include ${srcdir}../Makefile.program
 
+cleanall::
+	rm -f ${UPDOWN_PROGRAM} ${PROGRAM}
+
 programs: ${PROGRAM}
-
-
 ifeq ($(USE_IPROUTE2),false)
-echo "Cannot build _updown.netkey without USE_IPROUTE2, aborted"
-exit 1
+	echo "Cannot build _updown.netkey without USE_IPROUTE2, aborted"
+	exit 1
 else
-UPDOWN_PROGRAM=_updown.ip2
+	UPDOWN_PROGRAM=_updown.ip2
 endif
 
 ${PROGRAM}: ${UPDOWN_PROGRAM}
 	cp ${UPDOWN_PROGRAM} ${PROGRAM}
 
-cleanall::
-	rm -f ${UPDOWN_PROGRAM} ${PROGRAM}
 
 
