fix XAUTH unbound integration only to query unbound pid if cisco xauth is used

diff --git a/programs/_updown.klips/_updown.ip2.in b/programs/_updown.klips/_updown.ip2.in
--- a/programs/_updown.klips/_updown.ip2.in
+++ b/programs/_updown.klips/_updown.ip2.in
@@ -3,7 +3,7 @@
 #
 # Copyright (C) 2003-2004 Nigel Metheringham
 # Copyright (C) 2002-2007 Michael Richardson <mcr@xelerance.com>
-# Copyright (C) 2003-2011 Tuomo Soini <tis@foobar.fi>
+# Copyright (C) 2003-2012 Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2003-2007 Paul Wouters <paul@xelerance.com>
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -220,100 +220,101 @@ downrule() {
 }
 
 updateresolvconf() {
-if [ -n "`pidof unbound`" ]; then
-    if [ -n "$PLUTO_CISCO_DNS_INFO" -a -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
-       echo "updating local nameserver for $PLUTO_CISCO_DOMAIN_INFO with $PLUTO_CISCO_DNS_INFO"
-       /usr/sbin/unbound-control forward_add $PLUTO_CISCO_DOMAIN_INFO $PLUTO_CISCO_DOMAIN_INFO
-       /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
-    fi
-    return
-fi
-
-if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
-    echo "updating resolvconf"
-    if [ -e "$OPENSWAN_RESOLV_CONF" ]; then
-        echo "Backup resolv.conf already exists, so doing nothing"
-        return 1
-    fi
-
-    if [ ! -e "$ORIG_RESOLV_CONF" ]; then
-        echo "resolv.conf does not exist, so doing nothing"
-        return 1
-    fi
-
-    cp -- $ORIG_RESOLV_CONF $OPENSWAN_RESOLV_CONF
-
-    RESOLVE_CONF="#Generated by Openswan (IPSec)"
-
-    if [ -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
-	if grep 'domain' $ORIG_RESOLV_CONF > /dev/null 2>&1 
-	then 
-	RESOLVE_CONF="$RESOLVE_CONF\ndomain $PLUTO_CISCO_DOMAIN_INFO\nsearch $PLUTO_CISCO_DOMAIN_INFO"
-	else
-	RESOLVE_CONF="$RESOLVE_CONF\nsearch $PLUTO_CISCO_DOMAIN_INFO"
-	fi
-    fi
-
     if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
-	for i in $PLUTO_CISCO_DNS_INFO; do
-		RESOLVE_CONF="$RESOLVE_CONF\nnameserver $i"
-	done
-   fi
+	if [ -n "`pidof unbound`" -a -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
+	    echo "updating local nameserver for $PLUTO_CISCO_DOMAIN_INFO with $PLUTO_CISCO_DNS_INFO"
+	    /usr/sbin/unbound-control forward_add $PLUTO_CISCO_DOMAIN_INFO $PLUTO_CISCO_DOMAIN_INFO
+	    /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
+	fi
+	return
+    fi
 
-   rm -f -- $ORIG_RESOLV_CONF
-   printf "$RESOLVE_CONF" > $ORIG_RESOLV_CONF
-   return $?
-else
-   echo "Updating resolv.conf is controlled by Network Manager"
-   return 0
-fi
+    if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
+	echo "updating resolvconf"
+	if [ -e "$OPENSWAN_RESOLV_CONF" ]; then
+            echo "Backup resolv.conf already exists, so doing nothing"
+            return 1
+	fi
+
+	if [ ! -e "$ORIG_RESOLV_CONF" ]; then
+            echo "resolv.conf does not exist, so doing nothing"
+            return 1
+	fi
+
+	cp -- $ORIG_RESOLV_CONF $OPENSWAN_RESOLV_CONF
+
+	RESOLVE_CONF="#Generated by Openswan (IPSec)"
+
+	if [ -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
+	    if grep 'domain' $ORIG_RESOLV_CONF > /dev/null 2>&1 
+	    then 
+		RESOLVE_CONF="$RESOLVE_CONF\ndomain $PLUTO_CISCO_DOMAIN_INFO\nsearch $PLUTO_CISCO_DOMAIN_INFO"
+	    else
+		RESOLVE_CONF="$RESOLVE_CONF\nsearch $PLUTO_CISCO_DOMAIN_INFO"
+	    fi
+	fi
+
+	if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
+	    for i in $PLUTO_CISCO_DNS_INFO; do
+		RESOLVE_CONF="$RESOLVE_CONF\nnameserver $i"
+	    done
+	fi
+
+	rm -f -- $ORIG_RESOLV_CONF
+	printf "$RESOLVE_CONF" > $ORIG_RESOLV_CONF
+	return $?
+    else
+	echo "Updating resolv.conf is controlled by Network Manager"
+	return 0
+    fi
 }
 
 restoreresolvconf() {
-if [ -n "`pidof unbound`" ]; then
-    if [ -n "$PLUTO_CISCO_DNS_INFO" ]
-        echo "flushing local nameserver of $PLUTO_CISCO_DOMAIN_INFO"
-        /usr/sbin/unbound-control forward_remove $PLUTO_CISCO_DOMAIN_INFO
-        /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
-    return
-fi
-
-if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
-    echo "restoring resolvconf"
-
-    if [ ! -e "$OPENSWAN_RESOLV_CONF" ]; then
-	echo "Problem in restoring the resolv.conf, as there is no backup file"
-	return 2
+    if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
+	if [ -n "`pidof unbound`" ]; then
+            echo "flushing local nameserver of $PLUTO_CISCO_DOMAIN_INFO"
+            /usr/sbin/unbound-control forward_remove $PLUTO_CISCO_DOMAIN_INFO
+            /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
+	fi
+	return
     fi
 
-    if grep 'Openswan' $ORIG_RESOLV_CONF > /dev/null 2>&1 
-    then
-	cp -- "$OPENSWAN_RESOLV_CONF" $ORIG_RESOLV_CONF
+    if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
+	echo "restoring resolvconf"
+
+	if [ ! -e "$OPENSWAN_RESOLV_CONF" ]; then
+	    echo "Problem in restoring the resolv.conf, as there is no backup file"
+	    return 2
+	fi
+
+	if grep 'Openswan' $ORIG_RESOLV_CONF > /dev/null 2>&1 
+	then
+	    cp -- "$OPENSWAN_RESOLV_CONF" $ORIG_RESOLV_CONF
+	else
+	    echo "Current resolv.conf is not generated by Openswan, so doing nothing"
+	fi
+
+	rm -f -- "$OPENSWAN_RESOLV_CONF"
+	return 0
     else
-	echo "Current resolv.conf is not generated by Openswan, so doing nothing"
+	# Here disconnect signal is sent to NetworkManager
+	# whenever an already established connection is being terminated.
+	unset openswan_reason
+	unset PLUTO_CISCO_DOMAIN_INFO
+	unset PLUTO_CISCO_DNS_INFO
+	unset PLUTO_PEER_BANNER
+	unset PLUTO_MY_SOURCEIP
+	unset PLUTO_PEER
+	echo "Restoring resolv.conf is controlled by Network Manager"
+	disconnectNM
     fi
-
-    rm -f -- "$OPENSWAN_RESOLV_CONF"
-    return 0
-else
-# Here disconnect signal is sent to NetworkManager
-# whenever an already established connection is being terminated.
-    unset openswan_reason
-    unset PLUTO_CISCO_DOMAIN_INFO
-    unset PLUTO_CISCO_DNS_INFO
-    unset PLUTO_PEER_BANNER
-    unset PLUTO_MY_SOURCEIP
-    unset PLUTO_PEER
-    echo "Restoring resolv.conf is controlled by Network Manager"
-    disconnectNM
-fi
 }
 
 disconnectNM() {
-# This will be called whenever a connection fails to establish 
-# due to a state (either phase 1, xauth phase, or phase 2) fails.
-# This will send a singal to NetworkManager over dbus so that NM
-# can clear up coonnections.
+    # This will be called whenever a connection fails to establish 
+    # due to a state (either phase 1, xauth phase, or phase 2) fails.
+    # This will send a singal to NetworkManager over dbus so that NM
+    # can clear up coonnections.
     openswan_reason=disconnect
     export openswan_reason
     echo "sending disconnect signal to NetworkManager"
diff --git a/programs/_updown.netkey/_updown.netkey.in b/programs/_updown.netkey/_updown.netkey.in
--- a/programs/_updown.netkey/_updown.netkey.in
+++ b/programs/_updown.netkey/_updown.netkey.in
@@ -5,7 +5,7 @@
 # Copyright (C) 2003-2004 Nigel Metheringham
 # Copyright (C) 2002-2007 Michael Richardson <mcr@xelerance.com>
 # Copyright (C) 2007-2008 Paul Wouters <paul@xelerance.com>
-# Copyright (C) 2003-2010 Tuomo Soini <tis@foobar.fi>
+# Copyright (C) 2003-2012 Tuomo Soini <tis@foobar.fi>
 # 
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -189,122 +189,122 @@ downroute() {
 }
 
 updateresolvconf() {
-if [ -n "`pidof unbound`" ]; then
-    if [ -n "$PLUTO_CISCO_DNS_INFO" -a -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
-       echo "updating local nameserver for $PLUTO_CISCO_DOMAIN_INFO with $PLUTO_CISCO_DNS_INFO"
-       /usr/sbin/unbound-control forward_add $PLUTO_CISCO_DOMAIN_INFO $PLUTO_CISCO_DOMAIN_INFO
-       /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
-    fi
-    return
-fi
-
-if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
-    echo "updating resolvconf"
-
-    if [ ! -e "$ORIG_RESOLV_CONF" ]; then
-        echo "resolv.conf does not exist, so doing nothing"
-        return 1
-    fi
-
-    if [ -e "$OPENSWAN_RESOLV_CONF" ]; then
-	if grep 'Openswan' $ORIG_RESOLV_CONF > /dev/null 2>&1
-	then
-	    echo "Current resolv.conf is generated by Openswan, and backup resolv.conf already exists, so doing nothing"
-	    return 1
-	else
-            echo "backup resolv.conf exists, but current resolv.conf is not generated by Openswan"
-	fi
-    fi
-
-    rm -f $OPENSWAN_RESOLV_CONF
-    cp -- $ORIG_RESOLV_CONF $OPENSWAN_RESOLV_CONF
-
-    RESOLVE_CONF="#Generated by Openswan (IPSec)"
-
-    if [ -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
-	if grep 'domain' $ORIG_RESOLV_CONF > /dev/null 2>&1 
-	then 
-	RESOLVE_CONF="$RESOLVE_CONF\ndomain $PLUTO_CISCO_DOMAIN_INFO\nsearch $PLUTO_CISCO_DOMAIN_INFO"
-	else
-	RESOLVE_CONF="$RESOLVE_CONF\nsearch $PLUTO_CISCO_DOMAIN_INFO"
-	fi
-    fi
-
     if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
-	for i in $PLUTO_CISCO_DNS_INFO; do
+	if [ -n "`pidof unbound`" -a -n "$PLUTO_CISCO_DOMAIN_INFO"  ]; then
+	    echo "updating local nameserver for $PLUTO_CISCO_DOMAIN_INFO with $PLUTO_CISCO_DNS_INFO"
+	    /usr/sbin/unbound-control forward_add $PLUTO_CISCO_DOMAIN_INFO $PLUTO_CISCO_DOMAIN_INFO
+	    /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
+	fi
+	return
+    fi
+
+    if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
+	echo "updating resolvconf"
+
+	if [ ! -e "$ORIG_RESOLV_CONF" ]; then
+            echo "resolv.conf does not exist, so doing nothing"
+            return 1
+	fi
+
+	if [ -e "$OPENSWAN_RESOLV_CONF" ]; then
+	    if grep 'Openswan' $ORIG_RESOLV_CONF > /dev/null 2>&1
+	    then
+		echo "Current resolv.conf is generated by Openswan, and backup resolv.conf already exists, so doing nothing"
+		return 1
+	    else
+		echo "backup resolv.conf exists, but current resolv.conf is not generated by Openswan"
+	    fi
+	fi
+
+	rm -f $OPENSWAN_RESOLV_CONF
+	cp -- $ORIG_RESOLV_CONF $OPENSWAN_RESOLV_CONF
+
+	RESOLVE_CONF="#Generated by Openswan (IPSec)"
+
+	if [ -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
+	    if grep 'domain' $ORIG_RESOLV_CONF > /dev/null 2>&1 
+	    then 
+		RESOLVE_CONF="$RESOLVE_CONF\ndomain $PLUTO_CISCO_DOMAIN_INFO\nsearch $PLUTO_CISCO_DOMAIN_INFO"
+	    else
+		RESOLVE_CONF="$RESOLVE_CONF\nsearch $PLUTO_CISCO_DOMAIN_INFO"
+	    fi
+	fi
+
+	if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
+	    for i in $PLUTO_CISCO_DNS_INFO; do
 		RESOLVE_CONF="$RESOLVE_CONF\nnameserver $i"
-	done
-   fi
+	    done
+	fi
 
-   ORIG_NAMESERVER=`grep -m 1 ^nameserver $ORIG_RESOLV_CONF`
-   RESOLVE_CONF="$RESOLVE_CONF\n$ORIG_NAMESERVER"
+	ORIG_NAMESERVER=`grep -m 1 ^nameserver $ORIG_RESOLV_CONF`
+	RESOLVE_CONF="$RESOLVE_CONF\n$ORIG_NAMESERVER"
 
-   rm -f -- $ORIG_RESOLV_CONF
-   printf "$RESOLVE_CONF" > $ORIG_RESOLV_CONF
-   return $?
+	rm -f -- $ORIG_RESOLV_CONF
+	printf "$RESOLVE_CONF" > $ORIG_RESOLV_CONF
+	return $?
 
-else
-   echo "Updating resolv.conf is controlled by Network Manager"
-   openswan_reason=connect
-   export openswan_reason
-   export PLUTO_CISCO_DOMAIN_INFO
-   export PLUTO_CISCO_DNS_INFO
-   export PLUTO_PEER_BANNER
-   export PLUTO_MY_SOURCEIP
-   export PLUTO_PEER
+    else
+	echo "Updating resolv.conf is controlled by Network Manager"
+	openswan_reason=connect
+	export openswan_reason
+	export PLUTO_CISCO_DOMAIN_INFO
+	export PLUTO_CISCO_DNS_INFO
+	export PLUTO_PEER_BANNER
+	export PLUTO_MY_SOURCEIP
+	export PLUTO_PEER
 
-   /usr/libexec/nm-openswan-service-helper
+	/usr/libexec/nm-openswan-service-helper
 
-   return 0
-fi
+	return 0
+    fi
 }
 
 restoreresolvconf() {
-if [ -n "`pidof unbound`" ]; then
-    if [ -n "$PLUTO_CISCO_DNS_INFO" ]
-        echo "flushing local nameserver of $PLUTO_CISCO_DOMAIN_INFO"
-        /usr/sbin/unbound-control forward_remove $PLUTO_CISCO_DOMAIN_INFO
-        /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
-    fi
-    return
-fi
-
-if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
-    echo "restoring resolvconf"
-
-    if [ ! -e "$OPENSWAN_RESOLV_CONF" ]; then
-	echo "Problem in restoring the resolv.conf, as there is no backup file"
-	return 2
+    if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
+	if [ -n "`pidof unbound`" ]; then
+            echo "flushing local nameserver of $PLUTO_CISCO_DOMAIN_INFO"
+            /usr/sbin/unbound-control forward_remove $PLUTO_CISCO_DOMAIN_INFO
+            /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
+	fi
+	return
     fi
 
-    if grep 'Openswan' $ORIG_RESOLV_CONF > /dev/null 2>&1 
-    then
-	cp -- "$OPENSWAN_RESOLV_CONF" $ORIG_RESOLV_CONF
+    if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
+	echo "restoring resolvconf"
+
+	if [ ! -e "$OPENSWAN_RESOLV_CONF" ]; then
+	    echo "Problem in restoring the resolv.conf, as there is no backup file"
+	    return 2
+	fi
+
+	if grep 'Openswan' $ORIG_RESOLV_CONF > /dev/null 2>&1 
+	then
+	    cp -- "$OPENSWAN_RESOLV_CONF" $ORIG_RESOLV_CONF
+	else
+	    echo "Current resolv.conf is not generated by Openswan, so doing nothing"
+	fi
+
+	rm -f -- "$OPENSWAN_RESOLV_CONF"
+	return 0
     else
-	echo "Current resolv.conf is not generated by Openswan, so doing nothing"
+	# Here disconnect signal is sent to NetworkManager
+	# whenever an already established connection is being terminated.
+	unset openswan_reason
+	unset PLUTO_CISCO_DOMAIN_INFO
+	unset PLUTO_CISCO_DNS_INFO
+	unset PLUTO_PEER_BANNER
+	unset PLUTO_MY_SOURCEIP
+	unset PLUTO_PEER
+	echo "Restoring resolv.conf is controlled by Network Manager"
+	disconnectNM
     fi
-
-    rm -f -- "$OPENSWAN_RESOLV_CONF"
-    return 0
-else
-# Here disconnect signal is sent to NetworkManager
-# whenever an already established connection is being terminated.
-    unset openswan_reason
-    unset PLUTO_CISCO_DOMAIN_INFO
-    unset PLUTO_CISCO_DNS_INFO
-    unset PLUTO_PEER_BANNER
-    unset PLUTO_MY_SOURCEIP
-    unset PLUTO_PEER
-    echo "Restoring resolv.conf is controlled by Network Manager"
-    disconnectNM
-fi
 }
 
 disconnectNM() {
-# This will be called whenever a connection fails to establish 
-# due to a state (either phase 1, xauth phase, or phase 2) fails.
-# This will send a singal to NetworkManager over dbus so that NM
-# can clear up coonnections.
+    # This will be called whenever a connection fails to establish 
+    # due to a state (either phase 1, xauth phase, or phase 2) fails.
+    # This will send a singal to NetworkManager over dbus so that NM
+    # can clear up coonnections.
     openswan_reason=disconnect
     export openswan_reason
     echo "sending disconnect signal to NetworkManager"
