#840 - fixed nonce coalescing to deal with nonces of uneven sizes.
Signed-off-by: Michael Richardson <mcr@xelerance.com>

diff --git a/programs/_updown/_updown.in b/programs/_updown/_updown.in
--- a/programs/_updown/_updown.in
+++ b/programs/_updown/_updown.in
@@ -134,7 +134,7 @@ if [ -x @IPSEC_LIBDIR@/_updown.${PLUTO_STACK} ]
 then
 	exec @IPSEC_LIBDIR@/_updown.${PLUTO_STACK} $*
 else
-	echo "FATAL: Could not execute @IPSEC_LIBDIR@/_updown.${PLUTO_STACK} $*"
+	echo "FATAL: Could not execute @IPSEC_LIBDIR@/_updown.${PLUTO_STACK} $*" 1>&2
 fi
 
 exit 3;
